//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSeccion47.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(EmpleadoViewModels))]
    public partial class Empleado
    {
        public int EmpleadoID { get; set; }
        public string Ficha { get; set; }
        public string Nombre { get; set; }
        public string ApePa { get; set; }
        public string ApeMa { get; set; }
        public string RFC { get; set; }
        public string SituacionContractual { get; set; }
        public string UbicacionLaboral { get; set; }
        public string Rol { get; set; }
        public string Region { get; set; }
        public string ClaveDepartamento { get; set; }
        public int Nivel { get; set; }
        public string ClaveAsiste { get; set; }
        public string Domicilio { get; set; }
        public string Estado { get; set; }
        public string Ciudad { get; set; }
        public string TelefonoCasa { get; set; }
        public string TelefonoCelular { get; set; }
        public string CorreoElectronico { get; set; }
        public string Banco { get; set; }
        public string Sucursal { get; set; }
        public string NumeroCuenta { get; set; }
        public string ClaveInterbancaria { get; set; }
        public string Observaciones { get; set; }
        public Nullable<bool> Eliminacion { get; set; }
        public Nullable<System.DateTime> FechaInserta { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    }
}
