//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSeccion47.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vtaEmpleado
    {
        public int EmpleadoID { get; set; }
        public string Ficha { get; set; }
        public string Nombre { get; set; }
        public string SituacionContractual { get; set; }
        public string UbicacionLaboral { get; set; }
        public string Rol { get; set; }
        public string Region { get; set; }
        public int Nivel { get; set; }
        public string ClaveAsiste { get; set; }
        public Nullable<bool> Eliminacion { get; set; }
    }
}
